In [10]:
from numpy import *
from scipy.linalg import *

a = 0
b = 2
c = 3
d = 1

A = matrix([
    [a, a, a, a],
    [a, b, b, b],
    [a, b, c, c],
    [a, b, c, d]
])

E_21 = matrix([
    [1, 0, 0, 0],
    [-1, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

E_31 = matrix([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [-1, 0, 1, 0],
    [0, 0, 0, 1]
])

E_41 = matrix([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [-1, 0, 0, 1]
])

E_32 = matrix([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, -1, 1, 0],
    [0, 0, 0, 1]
])

E_42 = matrix([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, -1, 0, 1]
])

E_43 = matrix([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, -1, 1]
])

print(E_43 * E_42 * E_32 * E_41 * E_31 * E_21 * A)



[[ 0  0  0  0]
 [ 0  2  2  2]
 [ 0  0  1  1]
 [ 0  0  0 -2]]
