In [24]:
from numpy import *
from scipy.linalg import *

set_printoptions(precision=3, suppress=True)

A = matrix([
    [1,2,2],
    [0,1,4],
    [3,3,6]
])

I = identity(3)

aug = concatenate((A,I), axis=1)

E_31 = matrix([
    [1 ,0,0],
    [0 ,1,0],
    [-3,0,1]
])

print(E_31*aug)
print()

E_32 = matrix([
    [1,0,0],
    [0,1,0],
    [0,3,1]
])

print(E_32*E_31*aug)
print()

E_23 = matrix([
    [1,0, 0],
    [0,1,-1/3],
    [0,0, 1]
])

print(E_23*E_32*E_31*aug)
print()

E_13 = matrix([
    [1,0,-1/6],
    [0,1, 0],
    [0,0, 1]
])

print(E_13*E_23*E_32*E_31*aug)
print()

E_12 = matrix([
    [1,-2,0],
    [0, 1,0],
    [0, 0,1]
])

print(E_12*E_13*E_23*E_32*E_31*aug)
print()

D_33 = matrix([
    [1,0,   0 ],
    [0,1,   0 ],
    [0,0, 1/12]
])

print(D_33*E_12*E_13*E_23*E_32*E_31)
print()


[[ 1.  2.  2.  1.  0.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0. -3.  0. -3.  0.  1.]]

[[ 1.  2.  2.  1.  0.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0. 12. -3.  3.  1.]]

[[ 1.     2.     2.     1.     0.     0.   ]
 [ 0.     1.     0.     1.     0.    -0.333]
 [ 0.     0.    12.    -3.     3.     1.   ]]

[[ 1.     2.     0.     1.5   -0.5   -0.167]
 [ 0.     1.     0.     1.     0.    -0.333]
 [ 0.     0.    12.    -3.     3.     1.   ]]

[[ 1.     0.     0.    -0.5   -0.5    0.5  ]
 [ 0.     1.     0.     1.     0.    -0.333]
 [ 0.     0.    12.    -3.     3.     1.   ]]

[[-0.5   -0.5    0.5  ]
 [ 1.     0.    -0.333]
 [-0.25   0.25   0.083]]

