In [13]:
from numpy import *
from scipy.linalg import *

set_printoptions(precision=3, suppress=True)

A = matrix([
    [2,1,1],
    [4,0,2],
    [6,3,5]
])

E_21 = matrix([
    [1,0,0],
    [-2,1,0],
    [0,0,1]
])

print(E_21*A)
print()

E_31 = matrix([
    [1,0,0],
    [0,1,0],
    [-3,0,1]
])

print(E_31*E_21*A)
print()

print(inv(E_31*E_21)*E_31*E_21*A)
print()


[[ 2  1  1]
 [ 0 -2  0]
 [ 6  3  5]]

[[ 2  1  1]
 [ 0 -2  0]
 [ 0  0  2]]

[[2. 1. 1.]
 [4. 0. 2.]
 [6. 3. 5.]]

