In [4]:
from numpy import *

A = matrix([
    [1, 2],
    [3, 7],
    [-2, -3]
])

b = matrix([
    [1],
    [-2],
    [3]
])

ATA = A.T * A

print("ATA = ")
print(ATA)

ATA_inv = linalg.inv(ATA)

print("ATA_inv = ")
print(ATA_inv)

ATb = A.T * b

print("ATb = ")
print(ATb)

xhat = ATA_inv * ATb

print("xhat = ")
            

ATA = 
[[14 29]
 [29 62]]
ATA_inv = 
[[ 2.2962963  -1.07407407]
 [-1.07407407  0.51851852]]
ATb = 
[[-11]
 [-21]]
xhat = 
